site_name:           Docile.jl
repo_url:            https://github.com/MichaelHatherly/Docile.jl
site_description:    Julia package documentation system.
site_author:         Michael Hatherly
theme:               flatly
markdown_extensions: [tables, fenced_code]
pages:
    - ['index.md', 'Introduction']
    - ['manual.md', 'Manual', 'Overview']
    - ['syntax.md', 'Manual', 'Syntax']
    - ['api/Docile.md', 'API', 'Docile']
    - ['api/Docile.Interface.md', 'API', 'Docile.Interface']
    - ['api/index.md', 'API', 'Index']
